# Generated by Django 3.2.7 on 2021-09-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_type', models.CharField(max_length=50)),
                ('store_id', models.CharField(max_length=50)),
                ('store_name', models.CharField(max_length=200)),
                ('store_address', models.TextField()),
                ('store_city', models.CharField(max_length=50)),
                ('store_state', models.CharField(max_length=50)),
                ('store_zip', models.CharField(max_length=20)),
                ('store_phone', models.CharField(max_length=20)),
                ('store_latitude', models.CharField(default=None, max_length=20)),
                ('store_logitude', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
