# Generated by Django 3.2.7 on 2021-09-23 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2021, 9, 23)),
            preserve_default=False,
        ),
    ]
