# Generated by Django 3.2.7 on 2021-09-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_longitude',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
