# Generated by Django 3.2.7 on 2021-09-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210923_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_zip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
